name: Phonzia zone
markdown: redcarpet
pygments: true
github: https://www.github.com/phonzia
about: This is phonzia's blog.
urls:
    - text: github
      url: https://github.com/phonzia
    - text: email
      url: mailto:phonzia@gmail.com
