name: 和光
markdown: redcarpet
redcarpet :
  extensions : ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlighter"]
highlighter : pygments
pygments: true
github: https://www.github.com/phonzia
about: This is phonzia's blog.
urls:
    - text: github
      url: https://github.com/phonzia
    - text: email
      url: mailto:phonzia@gmail.com
