name: Phonzia
description : 专注是唯一的救赎
markdown: redcarpet
redcarpet :
  extensions : ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlighter"]
permalink: /:year/:month/:title
#paginate: 5
excerpt_separator: <!--more-->
highlighter : pygments
github: https://www.github.com/phonzia
about: This is phonzia's blog.
urls:
    - text: github
      url: phonzia
    - text: email
      url: mailto:phonzia@gmail.com
